name: fourface_id_ocr
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # OCR
  camera: ^0.10.5+2
  permission_handler: ^10.4.3
  flutter_tesseract_ocr: ^0.4.23
#  google_mlkit_commons: ^0.5.0
  google_ml_kit: ^0.12.0

  # REST API
  dio: ^5.1.2
  logger: ^1.3.0
  pretty_dio_logger: ^1.3.1
  http: ^1.1.0

  # state management
  flutter_riverpod: ^2.3.6

  # util
  timezone: ^0.9.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  get_it: ^7.6.0
  flutter_dotenv: ^5.0.2
  collection: ^1.17.1
  intl: ^0.18.0
  image: ^4.0.17

  # others
  age_calculator: ^1.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  freezed: ^2.3.4
  json_serializable: ^6.7.0

  build_runner: ^2.4.4
  flutter_gen_runner: ^5.3.1

flutter:
  uses-material-design: true

  assets:
    # .env
    - assets/env/.env.dev
